include:
  - board: seeeduino_xiao_ble
    shield: LATIN_dongle

  - board: seeeduino_xiao_ble
    shield: LATIN
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT=y

  - board: seeeduino_xiao_ble
    shield: settings_reset
