include:
  # 接收器固件（插电脑）
  - board: seeeduino_xiao_ble
    shield: LATIN_dongle

  # 单键盘固件（连接收器）
  - board: seeeduino_xiao_ble
    shield: LATIN
    cmake-args: -DCONFIG_ZMK_SPLIT=n -DCONFIG_ZMK_BLE_PERIPHERAL=y

  # 重置用（可选）
  - board: seeeduino_xiao_ble
    shield: settings_reset
